apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    app: tiers
    tier: backend
spec:
  capacity:
   storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
   path: /mnt/pod/mysql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-volume
  labels:
    app: tiers
    tier: frontend
spec:
  capacity:
   storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
   path: /mnt/pod/wordpress
    
